### ISSUE TITLE
Sorry! Pls read

### ISSUE THREAD

**Issue by Nim1com** [Skybot-dev/Skybot-rewrite#35]
Hello
I would like to know can i use this as a bot that i host since youre bot is offline and the MIT lisence needs a user to ask the creator that can they use is publicly?

Thank you for reading!

**Comment by lolieg** [comment]
The Bot doesn't seem to be offline, but sure you can host it yourself! There is a "description" on how to in the readme too.

**Comment by Nim1com** [comment]
I have the bot running privatly and made changes but the changes dont make
a difference at the features of the bot. I am making a version that i can
commit to help this project.—

**Comment by pjones123** [comment]
> I have the bot running privatly and made changes but the changes dont make a difference at the features of the bot. I am making a version that i can commit to help this project.—

I'm slightly confused as to what you're asking here. Could you explain a little more please?

**Comment by Nim1com** [comment]
Mit just wants consent.

**Comment by pjones123** [comment]
So everything's fine now?

**Comment by Nim1com** [comment]
Yes
