### ISSUE TITLE
every command that requires ign just says that the account doesnt exist

### ISSUE THREAD

**Issue by KyleTheDev** [Skybot-dev/Skybot-rewrite#47]
Hi, I've tried a few commands and every command I try it says this
![image](https://user-images.githubusercontent.com/75298673/153742772-36cddb3c-54a1-409c-911b-72bc49a9bb6b.png)
Plus there's issues in here 
![image](https://user-images.githubusercontent.com/75298673/153742802-15706f6b-c5a8-43b6-b6dd-3b78533a5a50.png)
Console log says 
"200 + {'success': False, 'message': 'invalid api key/hypixel api error'}
Malformed uuid or username; 930aa39d62e0457fa0117c0d70e6ed43"

My hypixel api key im using is correct tho, how can I fix this?

**Comment by KyleTheDev** [comment]
EDIT: 
Fixed api key error by updating a few things the malformed uuid or username error's still there and commands still say user doesnt exist so someone help
![image](https://user-images.githubusercontent.com/75298673/153743011-32ced1e4-6243-4b03-9f52-377dbbc39222.png)

**Comment by pjones123** [comment]
This appears to be an issue with your machine/network. Can you please check the response of `https://mc-heads.net/minecraft/profile/930aa39d62e0457fa0117c0d70e6ed43`?

**Comment by KyleTheDev** [comment]
Im hosting the bot on repl.it how do I do that?

**Comment by KyleTheDev** [comment]
Fixed
